var lat;var lng;var map;var map2;var map3;var image='img/map/google_map_point.png';var styles=[{"stylers":[{"saturation":-100},{"gamma":1}]},{"elementType":"labels.text.stroke","stylers":[{"visibility":"off"}]},{"featureType":"poi.business","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"poi.business","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"poi.place_of_worship","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"poi.place_of_worship","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"geometry","stylers":[{"visibility":"simplified"}]},{"featureType":"water","stylers":[{"visibility":"on"},{"saturation":50},{"gamma":0},{"hue":"#50a5d1"}]},{"featureType":"administrative.neighborhood","elementType":"labels.text.fill","stylers":[{"color":"#333333"}]},{"featureType":"road.local","elementType":"labels.text","stylers":[{"weight":0.5},{"color":"#333333"}]},{"featureType":"transit.station","elementType":"labels.icon","stylers":[{"gamma":1},{"saturation":50}]}];var styles2=[{"stylers":[{"saturation":-100},{"gamma":1}]},{"elementType":"labels.text.stroke","stylers":[{"visibility":"off"}]},{"featureType":"poi.business","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"poi.business","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"poi.place_of_worship","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"poi.place_of_worship","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"geometry","stylers":[{"visibility":"simplified"}]},{"featureType":"water","stylers":[{"visibility":"on"},{"saturation":50},{"gamma":0},{"hue":"#50a5d1"}]},{"featureType":"administrative.neighborhood","elementType":"labels.text.fill","stylers":[{"color":"#333333"}]},{"featureType":"road.local","elementType":"labels.text","stylers":[{"weight":0.5},{"color":"#333333"}]},{"featureType":"transit.station","elementType":"labels.icon","stylers":[{"gamma":1},{"saturation":50}]}];jQuery.getJSON('http://maps.googleapis.com/maps/api/geocode/json?address=san francisco, CA 94102, US&sensor=false',function(data){lat=data.results[0].geometry.location.lat;lng=data.results[0].geometry.location.lng;}).complete(function(){dxmapLoadMap();dxmapLoadMap2();dxmapLoadMap3();});function attachSecretMessage(marker,message)
{var infowindow=new google.maps.InfoWindow({content:message});google.maps.event.addListener(marker,'click',function(){infowindow.open(map,marker);});}
function attachSecretMessage2(marker,message)
{var infowindow=new google.maps.InfoWindow({content:message});google.maps.event.addListener(marker,'click',function(){infowindow.open(map2,marker);});}
function attachSecretMessage3(marker,message)
{var infowindow=new google.maps.InfoWindow({content:message});google.maps.event.addListener(marker,'click',function(){infowindow.open(map3,marker);});}
window.dxmapLoadMap=function()
{var center=new google.maps.LatLng(lat,lng);var settings={mapTypeId:google.maps.MapTypeId.ROADMAP,zoom:14,draggable:true,scrollwheel:false,center:center,mapTypeControl:false,panControl:true,streetViewControl:false};map=new google.maps.Map(document.getElementById('googlemap_1'),settings);var marker=new google.maps.Marker({position:center,title:'Map title',map:map,icon:image});marker.setTitle('Map title'.toString());attachSecretMessage(marker,'');}
window.dxmapLoadMap2=function()
{var center=new google.maps.LatLng(lat,lng);var settings={mapTypeId:google.maps.MapTypeId.ROADMAP,zoom:3,draggable:true,scrollwheel:false,center:center,styles:styles,mapTypeControl:false,panControl:true,streetViewControl:false};map2=new google.maps.Map(document.getElementById('googlemap_2'),settings);var marker=new google.maps.Marker({position:center,title:'Map title',map:map2,icon:image});marker.setTitle('Map title'.toString());attachSecretMessage2(marker,'');}
window.dxmapLoadMap3=function()
{var center=new google.maps.LatLng(lat,lng);var settings={mapTypeId:google.maps.MapTypeId.ROADMAP,zoom:8,draggable:true,scrollwheel:false,center:center,styles:styles2,mapTypeControl:false,panControl:true,streetViewControl:false};map3=new google.maps.Map(document.getElementById('googlemap_3'),settings);var marker=new google.maps.Marker({position:center,title:'Map title',map:map3,icon:image});marker.setTitle('Map title'.toString());attachSecretMessage3(marker,'');}